### ISSUE TITLE
FedJax depends on TensorFlow Federated?

### ISSUE THREAD

**Issue by davidrpugh** [google/fedjax#218]
I am helping users install FedJax for use in their federated learning research projects and I noticed that installing FedJax is pulling in TensorFlow Federated (0.17) and TensorFlow (2.3). I don't see either of these listed as dependencies of FedJax so I am trying to understand why they are being pulled in by `pip install fedjax`.

**Comment by kho** [comment]
We pushed out v0.0.8 last night. TensorFlow Federated is no longer a dependency, and TensorFlow is now an optional dependency. Installing fedjax via pip will not pull TensorFlow, and an exception with instructions for installing TensorFlow will be printed when a feature requiring TensorFlow is being used.

Please feel free to try out the new release, and let us know if you still run into issues.
